---
abstract: 'Redis::CappedCollection module provides the fixed sized collections that have a auto-FIFO age-out feature.'
author:
  - 'TrackingSoft LLC <sgladkov@trackingsoft.com>'
test_requires:
  Data::UUID: '1.217'
  JSON::XS: '3.01'
  Net::EmptyPort: 0
  Sys::SigAction: 0.21
  Test::Exception: 0.31
  Test::NoWarnings: 1.04
  Test::RedisServer: 0.04
configure_requires:
  ExtUtils::MakeMaker: 0
build_requires:
  Data::UUID: '1.217'
  JSON::XS: '3.01'
  ExtUtils::MakeMaker: '0'
  Net::EmptyPort: '0'
  Sys::SigAction: 0.21
  Test::Exception: '0.31'
  Test::NoWarnings: 1.04
  Test::RedisServer: '0.04'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Redis-CappedCollection
no_index:
  directory:
    - t
    - inc
    - xt
provides:
  Redis::CappedCollection:
    file: lib/Redis/CappedCollection.pm
    version: 1.08
  Redis::CappedCollection::Util:
    file: lib/Redis/CappedCollection/Util.pm
    version: 1.08
requires:
  Const::Fast: 0.014
  Digest::SHA1: 2.13
  Mouse: '2.4.1'
  Params::Util: 1.07
  Redis: 1.976
  Try::Tiny: 0.18
  perl: 5.010
version: 1.08
resources:
  homepage: https://github.com/TrackingSoft/Redis-CappedCollection
  repository: git://github.com/TrackingSoft/Redis-CappedCollection.git
